import { generateConstants } from '../utils';

export default generateConstants([
  'USERS_SHOW',
  'USERS_CLEAR_ERROR',
  'USERS_INDEX(ASYNC)',

  'README_LOAD(ASYNC)',

  'SESSION_CREATE(ASYNC)',
  'SESSION_DESTROY',

  'PROJECT_INDEX(ASYNC)',
  'PROJECT_CREATE(ASYNC)',
  'PROJECT_SHOW(ASYNC)',

  'TYPE_INDEX(ASYNC)',
  'TYPE_INIT',
  'TYPE_CREATE(ASYNC)',
  'TYPE_SHOW',
  'TYPE_EDIT(ASYNC)',
  'TYPE_DELETE(ASYNC)',
  'TYPE_SET_SORT(ASYNC)',
  'TYPE_SET_DEFAULT(ASYNC)',

  'MODULE_INDEX(ASYNC)',
  'MODULE_CREATE(ASYNC)',
  'MODULE_SHOW',
  'MODULE_EDIT(ASYNC)',
  'MODULE_DELETE(ASYNC)',

  'ISSUE_INDEX(ASYNC)',
  'ISSUE_CREATE(ASYNC)',
  'ISSUE_OPTIONS(ASYNC)',
  'ISSUE_SHOW(ASYNC)',
  'ISSUE_EDIT(ASYNC)',
  'ISSUE_SET_ASSIGNEE(ASYNC)',
  'ISSUE_DELETE(ASYNC)',
  'ISSUE_DELETE_NOTIFY',

  'VERSION_INDEX(ASYNC)',
  'VERSION_CREATE(ASYNC)',
  'VERSION_SHOW',
  'VERSION_EDIT(ASYNC)',
  'VERSION_DELETE(ASYNC)',

  'FIELD_INDEX(ASYNC)',
  'FIELD_CREATE(ASYNC)',
  'FIELD_SHOW(ASYNC)',
  'FIELD_EDIT(ASYNC)',
  'FIELD_DELETE(ASYNC)',

  'SCREEN_INDEX(ASYNC)',
  'SCREEN_CREATE(ASYNC)',
  'SCREEN_SHOW',
  'SCREEN_EDIT(ASYNC)',
  'SCREEN_DELETE(ASYNC)',

  'WORKFLOW_INDEX(ASYNC)',
  'WORKFLOW_CREATE(ASYNC)',
  'WORKFLOW_SHOW',
  'WORKFLOW_EDIT(ASYNC)',
  'WORKFLOW_DELETE(ASYNC)',

  'WFCONFIG_INDEX(ASYNC)',
  'WFCONFIG_SAVE(ASYNC)',
  'WFCONFIG_STEP_CREATE',
  'WFCONFIG_STEP_EDIT',
  'WFCONFIG_STEP_DELETE',
  'WFCONFIG_ACTION_ADD',
  'WFCONFIG_ACTION_EDIT',
  'WFCONFIG_ACTION_DELETE',

  'STATE_INDEX(ASYNC)',
  'STATE_CREATE(ASYNC)',
  'STATE_SHOW',
  'STATE_EDIT(ASYNC)',
  'STATE_DELETE(ASYNC)',

  'RESOLUTION_INDEX(ASYNC)',
  'RESOLUTION_CREATE(ASYNC)',
  'RESOLUTION_SHOW',
  'RESOLUTION_EDIT(ASYNC)',
  'RESOLUTION_DELETE(ASYNC)',
  'RESOLUTION_SET_SORT(ASYNC)',
  'RESOLUTION_SET_DEFAULT(ASYNC)',

  'PRIORITY_INDEX(ASYNC)',
  'PRIORITY_CREATE(ASYNC)',
  'PRIORITY_SHOW',
  'PRIORITY_EDIT(ASYNC)',
  'PRIORITY_DELETE(ASYNC)',
  'PRIORITY_SET_SORT(ASYNC)',
  'PRIORITY_SET_DEFAULT(ASYNC)',

  'ROLE_INDEX(ASYNC)',
  'ROLE_CREATE(ASYNC)',
  'ROLE_SHOW',
  'ROLE_EDIT(ASYNC)',
  'ROLE_DELETE(ASYNC)',

  'ROLEACTOR_INDEX(ASYNC)',
  'ROLEACTOR_EDIT(ASYNC)',

  'ISSUE_INDEX(ASYNC)',
  'ISSUE_CREATE(ASYNC)',

  'ISSUE_SEARCHER_ADD(ASYNC)',
  'ISSUE_SEARCHER_DELETE(ASYNC)',

  'ISSUE_FILE_DELETE(ASYNC)',
  'ISSUE_FILE_ADD',

  'USER_INFO_FETCH(ASYNC)',

  'LOCALE_INITIALIZE',
  'LOCALE_CHANGE(ASYNC)'
]);
