import { generateConstants } from '../utils';

export default generateConstants([
  'USERS_SHOW',
  'USERS_CLEAR_ERROR',
  'USERS_INDEX(ASYNC)',

  'README_LOAD(ASYNC)',

  'SESSION_CREATE(ASYNC)',
  'SESSION_DESTROY',

  'PROJECT_INDEX(ASYNC)',
  'PROJECT_CREATE(ASYNC)',
  'PROJECT_SHOW(ASYNC)',

  'TYPE_INDEX(ASYNC)',
  'TYPE_INIT',
  'TYPE_CREATE(ASYNC)',
  'TYPE_SHOW(ASYNC)',
  'TYPE_EDIT(ASYNC)',
  'TYPE_DELETE(ASYNC)',
  'TYPE_DELETE_NOTIFY',
  'TYPE_SET_SORT(ASYNC)',
  'TYPE_SET_DEFAULT(ASYNC)',

  'FIELD_INDEX(ASYNC)',
  'FIELD_CREATE(ASYNC)',
  'FIELD_SHOW(ASYNC)',
  'FIELD_EDIT(ASYNC)',
  'FIELD_DELETE(ASYNC)',
  'FIELD_DELETE_NOTIFY',

  'SCREEN_INDEX(ASYNC)',
  'SCREEN_CREATE(ASYNC)',
  'SCREEN_SHOW(ASYNC)',
  'SCREEN_EDIT(ASYNC)',
  'SCREEN_DELETE(ASYNC)',
  'SCREEN_DELETE_NOTIFY',

  'WORKFLOW_INDEX(ASYNC)',
  'WORKFLOW_CREATE(ASYNC)',
  'WORKFLOW_SHOW(ASYNC)',
  'WORKFLOW_EDIT(ASYNC)',
  'WORKFLOW_DELETE(ASYNC)',
  'WORKFLOW_DELETE_NOTIFY',

  'STATE_INDEX(ASYNC)',
  'STATE_CREATE(ASYNC)',
  'STATE_SHOW(ASYNC)',
  'STATE_EDIT(ASYNC)',
  'STATE_DELETE(ASYNC)',
  'STATE_DELETE_NOTIFY',
  'STATE_SET_SORT(ASYNC)',
  'STATE_SET_DEFAULT(ASYNC)',

  'ISSUE_INDEX(ASYNC)',
  'ISSUE_CREATE(ASYNC)',

  'USER_INFO_FETCH(ASYNC)',

  'LOCALE_INITIALIZE',
  'LOCALE_CHANGE(ASYNC)'
]);
